name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API tests
        run: |
          mvn clean test -Dgroups=API || true  

      - name: Upload API Allure results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: allure-api
          path: target/allure-results

  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run UI tests
        run: |
          mvn clean test -Dgroups=UI || true  

      - name: Upload UI Allure results
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui
          path: target/allure-results

  deploy:
    needs: [test-api, test-ui]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download reports
        uses: actions/download-artifact@v4
        with:
          path: target/allure-results
          pattern: allure-*-results
          merge-multiple: true

      - name: Generate Allure report
        run: |
          mvn allure:report
          echo "Allure Report: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/" >> $GITHUB_STEP_SUMMARY

      - name: Rename Allure report to index.html
        run: |
         if [ -f target/allure-report/allure-maven.html ]; then
           mv target/allure-report/allure-maven.html target/allure-report/index.html
         fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          keep_files: true
          force_orphan: true
