name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run API tests
        run: |
          mvn clean test -Dgroups=API || true  

      - name: Upload API Allure results
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: allure-api
          path: target/allure-results

  test-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run UI tests
        run: |
          mvn clean test -Dgroups=UI || true  

      - name: Upload UI Allure results
        if: always()  
        uses: actions/upload-artifact@v4
        with:
          name: allure-ui
          path: target/allure-results

  deploy:
    needs: [test-api, test-ui]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Download API report
        uses: actions/download-artifact@v4
        with:
          name: allure-api
          path: target/api

      - name: Download UI report
        uses: actions/download-artifact@v4
        with:
          name: allure-ui
          path: target/ui

      - name: Merge Allure results
        run: |
          mkdir -p target/allure-results
          cp -r target/api/* target/allure-results/ || true
          cp -r target/ui/* target/allure-results/ || true

      - name: Generate Allure report
        run: mvn allure:report || true 

      - name: Deploy to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin
          keep_files: true
