name: test123

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy to GitHub Pages'
        required: true
        default: 'true'

jobs:
  test-api-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Replace secrets in rp.properties
        run: |
          sed -i "s/\${RP_LOGIN}/${{ secrets.RP_LOGIN }}/g" src/main/resources/rp.properties
          sed -i "s/\${RP_PASSWORD}/${{ secrets.RP_PASSWORD }}/g" src/main/resources/rp.properties    

      - name: Run API tests
        run: mvn clean test -Dgroups=API || true

      - name: Upload API Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

      - name: Run UI tests
        run: mvn clean test -Dgroups=UI || true

      - name: Upload UI Allure results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: target/allure-results

  deploy-report:
    runs-on: ubuntu-latest
    needs: [test-api-ui]
    if: always()
    permissions:
      pages: write
      id-token: write
      
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results
          path: allure-results

      - name: Allure Report action from marketplace
        uses: simple-elf/allure-report-action@v1.12
        with:
          allure_results: allure-results
          allure_history: allure-history
      
      - name: Deploy to GitHub Pages
        if: ${{ github.event.inputs.deploy == 'true' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history 
          force_orphan: false
          keep_files: true
